# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
            DEBUG: True
            DBUSER: $DBUSER
            DBPASSWD: $DBPASSWD

      - image: circleci/postgres:9.6.2
        name: db
        environment:
            POSTGRES_DB: expensedb


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install postgresql for primary container
          command: |
            pip install --upgrade pip
            sudo apt-get update
            pip install psycopg2
      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            cd expense
            python manage.py test -p test_*.py api.tests
      - run: 
          name: Run application deployment
          command: ./bin/deploy
