# Generated by Django 3.0 on 2020-01-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200131_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User'),
        ),
    ]
