# Generated by Django 3.0 on 2020-02-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200131_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
